apiVersion: run.ai/v2alpha1
kind: InteractiveWorkload
metadata:
  name: KKH-vscode
  namespace: runai-toxic-comments
spec:
  name:
    value: KKH-vscode
  image:
    value: registry.aisingapore.net/mlops-pub/kapitan-hull/code-server:0.2.0
  imagePullPolicy:
    value: Always
  command:
    value: >-
      /bin/sh -c "
      mkdir -p /toxic-comments-pvc/workspaces/KKH/vscode/local &&
      mkdir -p /toxic-comments-pvc/workspaces/KKH/vscode/config &&
      rm -rf ~/.local ~/.config &&
      ln -sf /toxic-comments-pvc/workspaces/KKH/vscode/local ~/.local &&
      ln -sf /toxic-comments-pvc/workspaces/KKH/vscode/config ~/.config &&
      ln -sf /toxic-comments-pvc/workspaces/KKH ~/workspace &&
      code-server --bind-addr 0.0.0.0:8080 --disable-telemetry ."
  cpu:
    value: '2'
  cpuLimit:
    value: '4'
  memory:
    value: 4G
  memoryLimit:
    value: 8G
  gpu:
    value: '0'
  environment:
    items:
      RUNAI_JOB_NAME:
        value: ${RUNAI_JOB_NAME}
      RUNAI_PROJECT:
        value: ${RUNAI_PROJECT}
  exposedUrls:
    items:
      url-0:
        value:
          containerPort: 8080
          customUrl: false
  pvcs:
    items:
      pvc-toxic-comments-pvc:
        value:
          claimName: toxic-comments-pvc
          existingPvc: true
          path: /toxic-comments-pvc
          readOnly: false
          readWriteMany: true
  username:
    value: KKH