apiVersion: run.ai/v2alpha1
kind: InteractiveWorkload
metadata:
  name: KKH-jupyterlab
  namespace: runai-toxic-comments
spec:
  name:
    value: KKH-jupyterlab
  image:
    value: registry.aisingapore.net/mlops-pub/kapitan-hull/jupyterlab-server:0.2.0
  imagePullPolicy:
    value: Always
  command:
    value: jupyter lab
  arguments:
    value: '--no-browser --ip=0.0.0.0 --allow-root'
  cpu:
    value: '2'
  cpuLimit:
    value: '4'
  memory:
    value: 4G
  memoryLimit:
    value: 8G
  gpu:
    value: '0'
  environment:
    items:
      RUNAI_JOB_NAME:
        value: ${RUNAI_JOB_NAME}
      RUNAI_PROJECT:
        value: ${RUNAI_PROJECT}
  exposedUrls:
    items:
      url-0:
        value:
          containerPort: 8888
          customUrl: false
  pvcs:
    items:
      pvc-toxic-comments-pvc:
        value:
          claimName: toxic-comments-pvc
          existingPvc: true
          path: /toxic-comments-pvc
          readOnly: false
          readWriteMany: true
  username:
    value: KKH