apiVersion: run.ai/v2alpha1
kind: TrainingWorkload
metadata:
  name: KKH-build-dataprep
  namespace: runai-toxic-comments
spec:
  environment:
    items:
      HARBOR_ROBOT_CREDS_JSON:
        value: SECRET:harbor-credentials,.dockerconfigjson
  name:
    value: KKH-build-dataprep
  image: 
    value: gcr.io/kaniko-project/executor:debug
  imagePullPolicy:
    value: IfNotPresent
  command: 
    value: >- 
      /bin/sh -c 
      "mkdir -p /kaniko/.docker;
      echo $HARBOR_ROBOT_CREDS_JSON > /kaniko/.docker/config.json;
      /kaniko/executor
      --context .
      --dockerfile ./docker/toxic-comments-severity-data-prep.Dockerfile
      --destination registry.aisingapore.net/aiap-15-dsp/toxic/data-prep:runai-yaml-build"
  workingDir:
    value: /toxic-comments-pvc/workspaces/KKH/toxic-comments-severity
  cpu:
    value: '4'
  memory:
    value: 6G
  pvcs:
    items:
      pvc-toxic-comments-pvc:
        value: 
          claimName: toxic-comments-pvc
          existingPvc: true
          path: /toxic-comments-pvc
          readOnly: false
          readWriteMany: true
  username:
    value: KKH