apiVersion: run.ai/v2alpha1
kind: TrainingWorkload
metadata:
  name: KKH-data-prep
  namespace: runai-toxic-comments
spec:
  environment:
    items:
      WORKSPACE_NAME:
        value: KKH
  name: 
    value: KKH-data-prep
  image:
    value: registry.aisingapore.net/aiap-15-dsp/toxic/data-prep:runai-yaml-build
  imagePullPolicy:
    value: Always
  command:
    value: >-
      /bin/bash -c "source activate toxic-comments-severity && python src/process_data.py 
      process_data.raw_data_dir_path=../data/mnist-pngs-data-aisg
      process_data.processed_data_dir_path=../data/processed/mnist-pngs-data-aisg-processed"
  workingDir:
    value: /toxic-comments-pvc/workspaces/KKH/toxic-comments-severity
  cpu:
    value: '2'
  cpuLimit:
    value: '2'
  memory:
    value: 4G
  memoryLimit:
    value: 4G
  pvcs:
    items:
      pvc-toxic-comments-pvc:
        value:
          claimName: toxic-comments-pvc
          existingPvc: true
          path: /toxic-comments-pvc
          readOnly: false
          readWriteMany: true
  username:
    value: KKH
