apiVersion: run.ai/v2alpha1
kind: TrainingWorkload
metadata:
  name: KKH-hp-train
  namespace: runai-toxic-comments
spec:
  environment:
    items:
      WORKSPACE_NAME:
        value: KKH
      MLFLOW_EXP_NAME:
        value: KKH-toxic-comments-severity
      MLFLOW_TRACKING_URI:
        value: SECRET:mlflow-credentials,url
      MLFLOW_TRACKING_USERNAME:
        value: SECRET:mlflow-admin-credentials,username
      MLFLOW_TRACKING_PASSWORD:
        value: SECRET:mlflow-admin-credentials,password
  name:
    value: KKH-hp-train
  image: 
    value: registry.aisingapore.net/aiap-15-dsp/toxic/model-training:runai-yaml-build
  imagePullPolicy:
    value: Always
  command:
    value: >-
      /bin/bash -c "export MLFLOW_HPTUNING_TAG=$(date +%s) && source activate toxic-comments-severity && python src/train_model.py --multirun
      train_model.data_dir_path=../data/processed/mnist-pngs-data-aisg-processed
      train_model.model_checkpoint_dir_path=./models
      train_model.setup_mlflow=true train_model.epochs=3
      train_model.mlflow_tracking_uri=$MLFLOW_TRACKING_URI
      train_model.mlflow_exp_name=$MLFLOW_EXP_NAME"
  workingDir:
    value: /toxic-comments-pvc/workspaces/KKH/toxic-comments-severity
  cpu:
    value: '2'
  cpuLimit:
    value: '2'
  memory:
    value: 4G
  memoryLimit:
    value: 4G
  pvcs:
    items:
      pvc-toxic-comments-pvc:
        value:
          claimName: toxic-comments-pvc
          existingPvc: true
          path: /toxic-comments-pvc
          readOnly: false
          readWriteMany: true
  username:
    value: KKH